# Generated by Django 3.0.3 on 2020-02-22 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='results',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('ING1', models.CharField(max_length=100)),
                ('ING2', models.CharField(max_length=100)),
                ('ING3', models.CharField(max_length=100)),
                ('ING4', models.CharField(max_length=100)),
                ('ING5', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name_plural': 'recipes',
            },
        ),
    ]
